### ISSUE TITLE
v1.0.0 Checklist

### ISSUE THREAD

**Issue by karlomikus** [karlomikus/bar-assistant#18]
- [x] Finish OpenApi specification
- [x] Include substitute ingredients when showing what cocktails a user can make
- [ ] Test docker up/down with database migrations and seeding
- [x] Add the most "popular" cocktails
- [x] Check performance issues (opcache/remove file session)
- [ ] Add command to reset search indexes
- [x] Preselect some default ingredients for new deploys
- [x] Add demo environment
    - [x]  Generate specific api key for meilisearch
